# -*- coding: utf-8 -*-
"""Ai_Ml_Class_Dated_23032022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvr31ew-Dc3eMBve9-b4SzLKh5ESAhPo
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv('swedish_car_insurance - swedish_car_insurance.csv')
df.head()

plt.scatter(df['X'], df['Y'])

"""## Null check"""

df.isnull().sum()

sns.heatmap(df.isnull(),yticklabels=False,cmap='viridis')

X = df.iloc[:,:-1]
X

Y = df.iloc[:,1:]
Y

"""## Data Split"""

X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.3, random_state = 2)

LR = LinearRegression()

LR.fit(X_train,Y_train)

y_pred=LR.predict(X_test)

score=r2_score(Y_test, y_pred)
score

